

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
typedef void (*UniffiCallbackInterfaceEventListenerMethod0)(uint64_t uniffi_handle, RustBuffer event, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceEventListenerMethod0(
				UniffiCallbackInterfaceEventListenerMethod0 cb, uint64_t uniffi_handle, RustBuffer event, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, event, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD0
typedef void (*UniffiCallbackInterfaceLoggerMethod0)(uint64_t uniffi_handle, RustBuffer l, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLoggerMethod0(
				UniffiCallbackInterfaceLoggerMethod0 cb, uint64_t uniffi_handle, RustBuffer l, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, l, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BITCOIN_CHAIN_SERVICE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BITCOIN_CHAIN_SERVICE_METHOD0
typedef void (*UniffiCallbackInterfaceBitcoinChainServiceMethod0)(uint64_t uniffi_handle, RustBuffer address, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBitcoinChainServiceMethod0(
				UniffiCallbackInterfaceBitcoinChainServiceMethod0 cb, uint64_t uniffi_handle, RustBuffer address, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, address, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BITCOIN_CHAIN_SERVICE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BITCOIN_CHAIN_SERVICE_METHOD1
typedef void (*UniffiCallbackInterfaceBitcoinChainServiceMethod1)(uint64_t uniffi_handle, RustBuffer txid, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBitcoinChainServiceMethod1(
				UniffiCallbackInterfaceBitcoinChainServiceMethod1 cb, uint64_t uniffi_handle, RustBuffer txid, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, txid, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BITCOIN_CHAIN_SERVICE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BITCOIN_CHAIN_SERVICE_METHOD2
typedef void (*UniffiCallbackInterfaceBitcoinChainServiceMethod2)(uint64_t uniffi_handle, RustBuffer tx, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceBitcoinChainServiceMethod2(
				UniffiCallbackInterfaceBitcoinChainServiceMethod2 cb, uint64_t uniffi_handle, RustBuffer tx, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, tx, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD0
typedef void (*UniffiCallbackInterfaceStorageMethod0)(uint64_t uniffi_handle, RustBuffer key, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod0(
				UniffiCallbackInterfaceStorageMethod0 cb, uint64_t uniffi_handle, RustBuffer key, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, key, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD1
typedef void (*UniffiCallbackInterfaceStorageMethod1)(uint64_t uniffi_handle, RustBuffer key, RustBuffer value, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod1(
				UniffiCallbackInterfaceStorageMethod1 cb, uint64_t uniffi_handle, RustBuffer key, RustBuffer value, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, key, value, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD2
typedef void (*UniffiCallbackInterfaceStorageMethod2)(uint64_t uniffi_handle, RustBuffer offset, RustBuffer limit, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod2(
				UniffiCallbackInterfaceStorageMethod2 cb, uint64_t uniffi_handle, RustBuffer offset, RustBuffer limit, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, offset, limit, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD3
typedef void (*UniffiCallbackInterfaceStorageMethod3)(uint64_t uniffi_handle, RustBuffer payment, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod3(
				UniffiCallbackInterfaceStorageMethod3 cb, uint64_t uniffi_handle, RustBuffer payment, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, payment, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD4
typedef void (*UniffiCallbackInterfaceStorageMethod4)(uint64_t uniffi_handle, RustBuffer payment_id, RustBuffer metadata, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod4(
				UniffiCallbackInterfaceStorageMethod4 cb, uint64_t uniffi_handle, RustBuffer payment_id, RustBuffer metadata, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, payment_id, metadata, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD5
typedef void (*UniffiCallbackInterfaceStorageMethod5)(uint64_t uniffi_handle, RustBuffer id, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod5(
				UniffiCallbackInterfaceStorageMethod5 cb, uint64_t uniffi_handle, RustBuffer id, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, id, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD6
typedef void (*UniffiCallbackInterfaceStorageMethod6)(uint64_t uniffi_handle, RustBuffer txid, uint32_t vout, uint64_t amount_sats, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod6(
				UniffiCallbackInterfaceStorageMethod6 cb, uint64_t uniffi_handle, RustBuffer txid, uint32_t vout, uint64_t amount_sats, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, txid, vout, amount_sats, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD7
typedef void (*UniffiCallbackInterfaceStorageMethod7)(uint64_t uniffi_handle, RustBuffer txid, uint32_t vout, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod7(
				UniffiCallbackInterfaceStorageMethod7 cb, uint64_t uniffi_handle, RustBuffer txid, uint32_t vout, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, txid, vout, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD8
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD8
typedef void (*UniffiCallbackInterfaceStorageMethod8)(uint64_t uniffi_handle, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod8(
				UniffiCallbackInterfaceStorageMethod8 cb, uint64_t uniffi_handle, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD9
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STORAGE_METHOD9
typedef void (*UniffiCallbackInterfaceStorageMethod9)(uint64_t uniffi_handle, RustBuffer txid, uint32_t vout, RustBuffer payload, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStorageMethod9(
				UniffiCallbackInterfaceStorageMethod9 cb, uint64_t uniffi_handle, RustBuffer txid, uint32_t vout, RustBuffer payload, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return)
{
	return cb(uniffi_handle, txid, vout, payload, uniffi_future_callback, uniffi_callback_data, uniffi_out_return);
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
typedef struct UniffiVTableCallbackInterfaceEventListener {
    UniffiCallbackInterfaceEventListenerMethod0 onEvent;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceEventListener;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOGGER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOGGER
typedef struct UniffiVTableCallbackInterfaceLogger {
    UniffiCallbackInterfaceLoggerMethod0 log;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceLogger;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BITCOIN_CHAIN_SERVICE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BITCOIN_CHAIN_SERVICE
typedef struct UniffiVTableCallbackInterfaceBitcoinChainService {
    UniffiCallbackInterfaceBitcoinChainServiceMethod0 getAddressUtxos;
    UniffiCallbackInterfaceBitcoinChainServiceMethod1 getTransactionHex;
    UniffiCallbackInterfaceBitcoinChainServiceMethod2 broadcastTransaction;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceBitcoinChainService;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_STORAGE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_STORAGE
typedef struct UniffiVTableCallbackInterfaceStorage {
    UniffiCallbackInterfaceStorageMethod0 getCachedItem;
    UniffiCallbackInterfaceStorageMethod1 setCachedItem;
    UniffiCallbackInterfaceStorageMethod2 listPayments;
    UniffiCallbackInterfaceStorageMethod3 insertPayment;
    UniffiCallbackInterfaceStorageMethod4 setPaymentMetadata;
    UniffiCallbackInterfaceStorageMethod5 getPaymentById;
    UniffiCallbackInterfaceStorageMethod6 addDeposit;
    UniffiCallbackInterfaceStorageMethod7 deleteDeposit;
    UniffiCallbackInterfaceStorageMethod8 listDeposits;
    UniffiCallbackInterfaceStorageMethod9 updateDeposit;
    UniffiCallbackInterfaceFree uniffiFree;
} UniffiVTableCallbackInterfaceStorage;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CLONE_BITCOINCHAINSERVICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CLONE_BITCOINCHAINSERVICE
void* uniffi_breez_sdk_spark_fn_clone_bitcoinchainservice(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FREE_BITCOINCHAINSERVICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FREE_BITCOINCHAINSERVICE
void uniffi_breez_sdk_spark_fn_free_bitcoinchainservice(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_INIT_CALLBACK_VTABLE_BITCOINCHAINSERVICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_INIT_CALLBACK_VTABLE_BITCOINCHAINSERVICE
void uniffi_breez_sdk_spark_fn_init_callback_vtable_bitcoinchainservice(UniffiVTableCallbackInterfaceBitcoinChainService* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BITCOINCHAINSERVICE_GET_ADDRESS_UTXOS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BITCOINCHAINSERVICE_GET_ADDRESS_UTXOS
uint64_t uniffi_breez_sdk_spark_fn_method_bitcoinchainservice_get_address_utxos(void* ptr, RustBuffer address
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BITCOINCHAINSERVICE_GET_TRANSACTION_HEX
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BITCOINCHAINSERVICE_GET_TRANSACTION_HEX
uint64_t uniffi_breez_sdk_spark_fn_method_bitcoinchainservice_get_transaction_hex(void* ptr, RustBuffer txid
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BITCOINCHAINSERVICE_BROADCAST_TRANSACTION
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BITCOINCHAINSERVICE_BROADCAST_TRANSACTION
uint64_t uniffi_breez_sdk_spark_fn_method_bitcoinchainservice_broadcast_transaction(void* ptr, RustBuffer tx
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CLONE_BREEZSDK
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CLONE_BREEZSDK
void* uniffi_breez_sdk_spark_fn_clone_breezsdk(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FREE_BREEZSDK
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FREE_BREEZSDK
void uniffi_breez_sdk_spark_fn_free_breezsdk(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_ADD_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_ADD_EVENT_LISTENER
RustBuffer uniffi_breez_sdk_spark_fn_method_breezsdk_add_event_listener(void* ptr, uint64_t listener, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_CLAIM_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_CLAIM_DEPOSIT
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_claim_deposit(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_DISCONNECT
void uniffi_breez_sdk_spark_fn_method_breezsdk_disconnect(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_GET_INFO
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_GET_INFO
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_get_info(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_GET_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_GET_PAYMENT
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_get_payment(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_LIST_PAYMENTS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_LIST_PAYMENTS
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_list_payments(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_LIST_UNCLAIMED_DEPOSITS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_LIST_UNCLAIMED_DEPOSITS
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_list_unclaimed_deposits(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_LNURL_PAY
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_LNURL_PAY
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_lnurl_pay(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_POLL_LIGHTNING_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_POLL_LIGHTNING_SEND_PAYMENT
void uniffi_breez_sdk_spark_fn_method_breezsdk_poll_lightning_send_payment(void* ptr, RustBuffer payment_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_PREPARE_LNURL_PAY
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_PREPARE_LNURL_PAY
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_prepare_lnurl_pay(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_PREPARE_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_PREPARE_SEND_PAYMENT
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_prepare_send_payment(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_RECEIVE_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_RECEIVE_PAYMENT
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_receive_payment(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_REFUND_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_REFUND_DEPOSIT
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_refund_deposit(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_REMOVE_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_REMOVE_EVENT_LISTENER
int8_t uniffi_breez_sdk_spark_fn_method_breezsdk_remove_event_listener(void* ptr, RustBuffer id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_SEND_PAYMENT
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_send_payment(void* ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_SEND_PAYMENT_INTERNAL
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_SEND_PAYMENT_INTERNAL
uint64_t uniffi_breez_sdk_spark_fn_method_breezsdk_send_payment_internal(void* ptr, RustBuffer request, int8_t suppress_payment_event
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_SYNC_WALLET
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_BREEZSDK_SYNC_WALLET
RustBuffer uniffi_breez_sdk_spark_fn_method_breezsdk_sync_wallet(void* ptr, RustBuffer request, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CLONE_SDKBUILDER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CLONE_SDKBUILDER
void* uniffi_breez_sdk_spark_fn_clone_sdkbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FREE_SDKBUILDER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FREE_SDKBUILDER
void uniffi_breez_sdk_spark_fn_free_sdkbuilder(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CONSTRUCTOR_SDKBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CONSTRUCTOR_SDKBUILDER_NEW
void* uniffi_breez_sdk_spark_fn_constructor_sdkbuilder_new(RustBuffer config, RustBuffer mnemonic, void* storage, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_SDKBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_SDKBUILDER_BUILD
uint64_t uniffi_breez_sdk_spark_fn_method_sdkbuilder_build(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_SDKBUILDER_WITH_CHAIN_SERVICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_SDKBUILDER_WITH_CHAIN_SERVICE
uint64_t uniffi_breez_sdk_spark_fn_method_sdkbuilder_with_chain_service(void* ptr, void* chain_service
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_SDKBUILDER_WITH_LNURL_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_SDKBUILDER_WITH_LNURL_CLIENT
uint64_t uniffi_breez_sdk_spark_fn_method_sdkbuilder_with_lnurl_client(void* ptr, void* lnurl_client
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_SDKBUILDER_WITH_REST_CHAIN_SERVICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_SDKBUILDER_WITH_REST_CHAIN_SERVICE
uint64_t uniffi_breez_sdk_spark_fn_method_sdkbuilder_with_rest_chain_service(void* ptr, RustBuffer url, RustBuffer credentials
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CLONE_STORAGE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_CLONE_STORAGE
void* uniffi_breez_sdk_spark_fn_clone_storage(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FREE_STORAGE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FREE_STORAGE
void uniffi_breez_sdk_spark_fn_free_storage(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_INIT_CALLBACK_VTABLE_STORAGE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_INIT_CALLBACK_VTABLE_STORAGE
void uniffi_breez_sdk_spark_fn_init_callback_vtable_storage(UniffiVTableCallbackInterfaceStorage* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_GET_CACHED_ITEM
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_GET_CACHED_ITEM
uint64_t uniffi_breez_sdk_spark_fn_method_storage_get_cached_item(void* ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_SET_CACHED_ITEM
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_SET_CACHED_ITEM
uint64_t uniffi_breez_sdk_spark_fn_method_storage_set_cached_item(void* ptr, RustBuffer key, RustBuffer value
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_LIST_PAYMENTS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_LIST_PAYMENTS
uint64_t uniffi_breez_sdk_spark_fn_method_storage_list_payments(void* ptr, RustBuffer offset, RustBuffer limit
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_INSERT_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_INSERT_PAYMENT
uint64_t uniffi_breez_sdk_spark_fn_method_storage_insert_payment(void* ptr, RustBuffer payment
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_SET_PAYMENT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_SET_PAYMENT_METADATA
uint64_t uniffi_breez_sdk_spark_fn_method_storage_set_payment_metadata(void* ptr, RustBuffer payment_id, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_GET_PAYMENT_BY_ID
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_GET_PAYMENT_BY_ID
uint64_t uniffi_breez_sdk_spark_fn_method_storage_get_payment_by_id(void* ptr, RustBuffer id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_ADD_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_ADD_DEPOSIT
uint64_t uniffi_breez_sdk_spark_fn_method_storage_add_deposit(void* ptr, RustBuffer txid, uint32_t vout, uint64_t amount_sats
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_DELETE_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_DELETE_DEPOSIT
uint64_t uniffi_breez_sdk_spark_fn_method_storage_delete_deposit(void* ptr, RustBuffer txid, uint32_t vout
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_LIST_DEPOSITS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_LIST_DEPOSITS
uint64_t uniffi_breez_sdk_spark_fn_method_storage_list_deposits(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_UPDATE_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_METHOD_STORAGE_UPDATE_DEPOSIT
uint64_t uniffi_breez_sdk_spark_fn_method_storage_update_deposit(void* ptr, RustBuffer txid, uint32_t vout, RustBuffer payload
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
void uniffi_breez_sdk_spark_fn_init_callback_vtable_eventlistener(UniffiVTableCallbackInterfaceEventListener* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_INIT_CALLBACK_VTABLE_LOGGER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_INIT_CALLBACK_VTABLE_LOGGER
void uniffi_breez_sdk_spark_fn_init_callback_vtable_logger(UniffiVTableCallbackInterfaceLogger* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_CONNECT
uint64_t uniffi_breez_sdk_spark_fn_func_connect(RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_DEFAULT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_DEFAULT_CONFIG
RustBuffer uniffi_breez_sdk_spark_fn_func_default_config(RustBuffer network, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_DEFAULT_STORAGE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_DEFAULT_STORAGE
void* uniffi_breez_sdk_spark_fn_func_default_storage(RustBuffer data_dir, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_INIT_LOGGING
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_INIT_LOGGING
void uniffi_breez_sdk_spark_fn_func_init_logging(RustBuffer log_dir, RustBuffer app_logger, RustBuffer log_filter, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_PARSE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_FN_FUNC_PARSE
uint64_t uniffi_breez_sdk_spark_fn_func_parse(RustBuffer input
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUSTBUFFER_ALLOC
RustBuffer ffi_breez_sdk_spark_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_breez_sdk_spark_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUSTBUFFER_FREE
void ffi_breez_sdk_spark_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUSTBUFFER_RESERVE
RustBuffer ffi_breez_sdk_spark_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_U8
void ffi_breez_sdk_spark_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_U8
void ffi_breez_sdk_spark_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_U8
void ffi_breez_sdk_spark_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_breez_sdk_spark_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_I8
void ffi_breez_sdk_spark_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_I8
void ffi_breez_sdk_spark_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_I8
void ffi_breez_sdk_spark_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_I8
int8_t ffi_breez_sdk_spark_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_U16
void ffi_breez_sdk_spark_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_U16
void ffi_breez_sdk_spark_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_U16
void ffi_breez_sdk_spark_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_breez_sdk_spark_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_I16
void ffi_breez_sdk_spark_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_I16
void ffi_breez_sdk_spark_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_I16
void ffi_breez_sdk_spark_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_I16
int16_t ffi_breez_sdk_spark_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_U32
void ffi_breez_sdk_spark_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_U32
void ffi_breez_sdk_spark_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_U32
void ffi_breez_sdk_spark_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_breez_sdk_spark_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_I32
void ffi_breez_sdk_spark_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_I32
void ffi_breez_sdk_spark_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_I32
void ffi_breez_sdk_spark_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_I32
int32_t ffi_breez_sdk_spark_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_U64
void ffi_breez_sdk_spark_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_U64
void ffi_breez_sdk_spark_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_U64
void ffi_breez_sdk_spark_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_breez_sdk_spark_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_I64
void ffi_breez_sdk_spark_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_I64
void ffi_breez_sdk_spark_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_I64
void ffi_breez_sdk_spark_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_I64
int64_t ffi_breez_sdk_spark_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_F32
void ffi_breez_sdk_spark_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_F32
void ffi_breez_sdk_spark_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_F32
void ffi_breez_sdk_spark_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_F32
float ffi_breez_sdk_spark_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_F64
void ffi_breez_sdk_spark_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_F64
void ffi_breez_sdk_spark_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_F64
void ffi_breez_sdk_spark_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_F64
double ffi_breez_sdk_spark_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_POINTER
void ffi_breez_sdk_spark_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_POINTER
void ffi_breez_sdk_spark_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_POINTER
void ffi_breez_sdk_spark_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_POINTER
void* ffi_breez_sdk_spark_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_breez_sdk_spark_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_breez_sdk_spark_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_breez_sdk_spark_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_breez_sdk_spark_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_POLL_VOID
void ffi_breez_sdk_spark_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_CANCEL_VOID
void ffi_breez_sdk_spark_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_FREE_VOID
void ffi_breez_sdk_spark_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_RUST_FUTURE_COMPLETE_VOID
void ffi_breez_sdk_spark_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_CONNECT
uint16_t uniffi_breez_sdk_spark_checksum_func_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_DEFAULT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_DEFAULT_CONFIG
uint16_t uniffi_breez_sdk_spark_checksum_func_default_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_DEFAULT_STORAGE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_DEFAULT_STORAGE
uint16_t uniffi_breez_sdk_spark_checksum_func_default_storage(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_INIT_LOGGING
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_INIT_LOGGING
uint16_t uniffi_breez_sdk_spark_checksum_func_init_logging(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_PARSE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_FUNC_PARSE
uint16_t uniffi_breez_sdk_spark_checksum_func_parse(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BITCOINCHAINSERVICE_GET_ADDRESS_UTXOS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BITCOINCHAINSERVICE_GET_ADDRESS_UTXOS
uint16_t uniffi_breez_sdk_spark_checksum_method_bitcoinchainservice_get_address_utxos(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BITCOINCHAINSERVICE_GET_TRANSACTION_HEX
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BITCOINCHAINSERVICE_GET_TRANSACTION_HEX
uint16_t uniffi_breez_sdk_spark_checksum_method_bitcoinchainservice_get_transaction_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BITCOINCHAINSERVICE_BROADCAST_TRANSACTION
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BITCOINCHAINSERVICE_BROADCAST_TRANSACTION
uint16_t uniffi_breez_sdk_spark_checksum_method_bitcoinchainservice_broadcast_transaction(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_ADD_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_ADD_EVENT_LISTENER
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_add_event_listener(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_CLAIM_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_CLAIM_DEPOSIT
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_claim_deposit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_DISCONNECT
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_disconnect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_GET_INFO
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_GET_INFO
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_get_info(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_GET_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_GET_PAYMENT
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_get_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_LIST_PAYMENTS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_LIST_PAYMENTS
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_list_payments(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_LIST_UNCLAIMED_DEPOSITS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_LIST_UNCLAIMED_DEPOSITS
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_list_unclaimed_deposits(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_LNURL_PAY
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_LNURL_PAY
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_lnurl_pay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_POLL_LIGHTNING_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_POLL_LIGHTNING_SEND_PAYMENT
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_poll_lightning_send_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_PREPARE_LNURL_PAY
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_PREPARE_LNURL_PAY
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_prepare_lnurl_pay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_PREPARE_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_PREPARE_SEND_PAYMENT
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_prepare_send_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_RECEIVE_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_RECEIVE_PAYMENT
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_receive_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_REFUND_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_REFUND_DEPOSIT
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_refund_deposit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_REMOVE_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_REMOVE_EVENT_LISTENER
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_remove_event_listener(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_SEND_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_SEND_PAYMENT
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_send_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_SEND_PAYMENT_INTERNAL
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_SEND_PAYMENT_INTERNAL
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_send_payment_internal(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_SYNC_WALLET
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_BREEZSDK_SYNC_WALLET
uint16_t uniffi_breez_sdk_spark_checksum_method_breezsdk_sync_wallet(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_SDKBUILDER_BUILD
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_SDKBUILDER_BUILD
uint16_t uniffi_breez_sdk_spark_checksum_method_sdkbuilder_build(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_SDKBUILDER_WITH_CHAIN_SERVICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_SDKBUILDER_WITH_CHAIN_SERVICE
uint16_t uniffi_breez_sdk_spark_checksum_method_sdkbuilder_with_chain_service(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_SDKBUILDER_WITH_LNURL_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_SDKBUILDER_WITH_LNURL_CLIENT
uint16_t uniffi_breez_sdk_spark_checksum_method_sdkbuilder_with_lnurl_client(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_SDKBUILDER_WITH_REST_CHAIN_SERVICE
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_SDKBUILDER_WITH_REST_CHAIN_SERVICE
uint16_t uniffi_breez_sdk_spark_checksum_method_sdkbuilder_with_rest_chain_service(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_GET_CACHED_ITEM
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_GET_CACHED_ITEM
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_get_cached_item(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_SET_CACHED_ITEM
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_SET_CACHED_ITEM
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_set_cached_item(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_LIST_PAYMENTS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_LIST_PAYMENTS
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_list_payments(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_INSERT_PAYMENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_INSERT_PAYMENT
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_insert_payment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_SET_PAYMENT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_SET_PAYMENT_METADATA
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_set_payment_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_GET_PAYMENT_BY_ID
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_GET_PAYMENT_BY_ID
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_get_payment_by_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_ADD_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_ADD_DEPOSIT
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_add_deposit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_DELETE_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_DELETE_DEPOSIT
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_delete_deposit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_LIST_DEPOSITS
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_LIST_DEPOSITS
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_list_deposits(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_UPDATE_DEPOSIT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_STORAGE_UPDATE_DEPOSIT
uint16_t uniffi_breez_sdk_spark_checksum_method_storage_update_deposit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_CONSTRUCTOR_SDKBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_CONSTRUCTOR_SDKBUILDER_NEW
uint16_t uniffi_breez_sdk_spark_checksum_constructor_sdkbuilder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_EVENTLISTENER_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_EVENTLISTENER_ON_EVENT
uint16_t uniffi_breez_sdk_spark_checksum_method_eventlistener_on_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_LOGGER_LOG
#define UNIFFI_FFIDEF_UNIFFI_BREEZ_SDK_SPARK_CHECKSUM_METHOD_LOGGER_LOG
uint16_t uniffi_breez_sdk_spark_checksum_method_logger_log(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_BREEZ_SDK_SPARK_UNIFFI_CONTRACT_VERSION
uint32_t ffi_breez_sdk_spark_uniffi_contract_version(void
    
);
#endif

 void breez_sdk_spark_cgo_dispatchCallbackInterfaceBitcoinChainServiceMethod0(uint64_t uniffi_handle, RustBuffer address, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceBitcoinChainServiceMethod1(uint64_t uniffi_handle, RustBuffer txid, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceBitcoinChainServiceMethod2(uint64_t uniffi_handle, RustBuffer tx, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceBitcoinChainServiceFree(uint64_t handle);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod0(uint64_t uniffi_handle, RustBuffer key, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod1(uint64_t uniffi_handle, RustBuffer key, RustBuffer value, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod2(uint64_t uniffi_handle, RustBuffer offset, RustBuffer limit, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod3(uint64_t uniffi_handle, RustBuffer payment, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod4(uint64_t uniffi_handle, RustBuffer payment_id, RustBuffer metadata, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod5(uint64_t uniffi_handle, RustBuffer id, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod6(uint64_t uniffi_handle, RustBuffer txid, uint32_t vout, uint64_t amount_sats, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod7(uint64_t uniffi_handle, RustBuffer txid, uint32_t vout, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod8(uint64_t uniffi_handle, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageMethod9(uint64_t uniffi_handle, RustBuffer txid, uint32_t vout, RustBuffer payload, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFuture* uniffi_out_return);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceStorageFree(uint64_t handle);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceEventListenerMethod0(uint64_t uniffi_handle, RustBuffer event, void* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceEventListenerFree(uint64_t handle);
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceLoggerMethod0(uint64_t uniffi_handle, RustBuffer l, void* uniffi_out_return, RustCallStatus* callStatus );
 void breez_sdk_spark_cgo_dispatchCallbackInterfaceLoggerFree(uint64_t handle);

void breez_sdk_spark_uniffiFutureContinuationCallback(uint64_t, int8_t);
void breez_sdk_spark_uniffiFreeGorutine(uint64_t);
